### ISSUE TITLE
Page Refresh on Submit - Firefox

### ISSUE THREAD

**Issue by P1318699X** [CTEC3905/javascript-01#1]
The whole page will refresh on form submission if you're using Firefox instead of returning the updated text.

I have a workaround that can be put in the HTML:
**<form id="get-name" action="#" method="post" onsubmit="return false">**
Adding the **onsubmit="return false"** fixes the issue.

Don't suppose anyone knows how to fix this in the JS?
**event.preventDefault();** and **return false;** don't seem to work.

**Comment by DaveEveritt** [comment]
Thanks for identifying the issue. There's a pile of advice out there on this, but hardly any of it about getting it out of the HTML. Chrome handles this example as a courtesy to IE, but Firefox doesn't. I need to go through the material and find the best approach. Best source so far: https://support.mozilla.org/en-US/questions/952250

**Comment by DaveEveritt** [comment]
Just fixed. See the 'firefox-fix' branch. The only way I found so far is to handle the form submission differently depending on whether 'event' is defined or not - in IE and Chrome, it is a property of 'window', in FF, it's not.
